In [3]:
import gzip
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
from typing import Tuple, List
from tabulate import tabulate
from sklearn.linear_model import LinearRegression
from cov_read_module import cov_read

In [10]:
cov_reader = cov_read()
# df = cov_reader.build_result()

In [11]:
df = cov_reader.build_df("GSM2465633_M00018724_27wk_Liver.cov.txt.gz")

data/GSE93957_RAW/GSM2465633_M00018724_27wk_Liver.cov.txt.gz

In [12]:
df.head(20)

   chromosome    s_loc    e_loc  methyl_rate  s_depth  e_depth  CG site
0           7  3002649  3002649   100.000000        1        0    False
1           7  3002810  3002810   100.000000        1        0    False
2           7  3002819  3002819   100.000000        1        0    False
3           7  3002846  3002846   100.000000        1        0    False
4           7  3013401  3013401     0.000000        0        1    False
5           7  3015880  3015880    92.307692       12        1    False
6           7  3016074  3016074    38.461538        5        8     True
7           7  3016075  3016075     0.000000        0        1     True
8           7  3016118  3016118     7.692308        1       12     True
9           7  3016119  3016119   100.000000        1        0     True
10          7  3025715  3025715   100.000000        6        0     True
11          7  3025716  3025716     0.000000        0        3     True
12          7  3026181  3026181     0.000000        0        6     True
13          7  3026182  3026182   100.000000        3        0     True
14          7  3039855  3039855   100.000000        1        0    False
15          7  3044262  3044262     0.000000        0        2    False
16          7  3044412  3044412   100.000000        3        0    False
17          7  3046111  3046111   100.000000        6        0    False
18          7  3046128  3046128    66.666667        4        2    False
19          7  3046162  3046162     0.000000        0        6    False

In [14]:
def filter_dataframe(df, chromosome, start_loc, end_loc):
    """
    Filter the dataframe for the given chromosome and between start_loc and end_loc.
    
    Parameters:
    - df: pandas.DataFrame - The dataframe to filter.
    - chromosome: int - The chromosome number to filter by.
    - start_loc: int - The start location to filter by.
    - end_loc: int - The end location to filter by.
    
    Returns:
    - pandas.DataFrame - The filtered dataframe.
    """
    # Filter based on the conditions
    filtered_df = df[(df['chromosome'] == chromosome) & (df['s_loc'] >= start_loc) & (df['s_loc'] <= end_loc)]
    
    return filtered_df

In [20]:
# chromosome = int(input("Enter the chromosome number"))
# start_loc = int(input("Enter the starting location"))
# end_loc = int(input("Enter the end location"))

chromosome = 7
start_loc = 3002846
end_loc = 3046111

filtered_df = filter_dataframe(df, chromosome, start_loc, end_loc)

In [21]:
filtered_df.head(10)

Empty DataFrame
Columns: [chromosome, s_loc, e_loc, methyl_rate, s_depth, e_depth, CG site]
Index: []